# Generated by Django 2.2.13 on 2021-07-19 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20210719_1043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
